config/routes.rb
Rollcall::Application.routes.draw do
  get '/attendances/new', controller: 'attendances', action: 'new', as: 'new_attendance'
  post '/attendances', controller: 'attendances', action: 'create', as: 'attendances'

  get '/attendances', controller: 'attendances', action: 'index'
  get '/attendances/:id', controller: 'attendances', action: 'show', as: 'attendance'

  get '/attendances/:id/edit', controller: 'attendances', action: 'edit', as: 'edit_attendance'
  patch '/attendances/:id', controller: 'attendances', action: 'update'

  delete '/attendances/:id', controller: 'attendances', action: 'destroy'

  get '/students/new', controller: 'students', action: 'new', as: 'new_student'
  post '/students', controller: 'students', action: 'create', as: 'students'

  get '/students', controller: 'students', action: 'index'
  get '/students/:id', controller: 'students', action: 'show', as: 'student'

  get '/students/:id/edit', controller: 'students', action: 'edit', as: 'edit_student'
  patch '/students/:id', controller: 'students', action: 'update'

  delete '/students/:id', controller: 'students', action: 'destroy'

  get '/meetings/new', controller: 'meetings', action: 'new', as: 'new_meeting'
  post '/meetings', controller: 'meetings', action: 'create', as: 'meetings'

  get '/meetings', controller: 'meetings', action: 'index'
  get '/meetings/:id', controller: 'meetings', action: 'show', as: 'meeting'

  get '/meetings/:id/edit', controller: 'meetings', action: 'edit', as: 'edit_meeting'
  patch '/meetings/:id', controller: 'meetings', action: 'update'

  delete '/meetings/:id', controller: 'meetings', action: 'destroy'

  get '/courses/new', controller: 'courses', action: 'new', as: 'new_course'
  post '/courses', controller: 'courses', action: 'create', as: 'courses'

  get '/courses', controller: 'courses', action: 'index'
  get '/courses/:id', controller: 'courses', action: 'show', as: 'course'

  get '/courses/:id/edit', controller: 'courses', action: 'edit', as: 'edit_course'
  patch '/courses/:id', controller: 'courses', action: 'update'

  delete '/courses/:id', controller: 'courses', action: 'destroy'

  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def index
    @attendances = Attendance.all
  end

  def show
    @attendance = Attendance.find_by(id: params[:id])
  end

  def new
  end

  def create
    @attendance = Attendance.new
    @attendance.meeting_id = params[:meeting_id]
    @attendance.student_id = params[:student_id]

    if @attendance.save
      redirect_to attendances_url, notice: "Attendance created successfully."
    else
      render 'new'
    end
  end

  def edit
    @attendance = Attendance.find_by(id: params[:id])
  end

  def update
    @attendance = Attendance.find_by(id: params[:id])
    @attendance.meeting_id = params[:meeting_id]
    @attendance.student_id = params[:student_id]

    if @attendance.save
      redirect_to attendances_url, notice: "Attendance updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @attendance = Attendance.find_by(id: params[:id])
    @attendance.destroy

    redirect_to attendances_url, notice: "Attendance deleted."
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find_by(id: params[:id])
  end

  def new
  end

  def create
    @course = Course.new
    @course.department = params[:department]
    @course.number = params[:number]
    @course.title = params[:title]

    if @course.save
      redirect_to courses_url, notice: "Course created successfully."
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find_by(id: params[:id])
  end

  def update
    @course = Course.find_by(id: params[:id])
    @course.department = params[:department]
    @course.number = params[:number]
    @course.title = params[:title]

    if @course.save
      redirect_to courses_url, notice: "Course updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find_by(id: params[:id])
    @course.destroy

    redirect_to courses_url, notice: "Course deleted."
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    @meetings = Meeting.all
  end

  def show
    @meeting = Meeting.find_by(id: params[:id])
  end

  def new
   @courses = Course.all
  end

  def create
    @meeting = Meeting.new
    @meeting.held_on = params[:held_on]
    @meeting.course_id = params[:course_id]

    if @meeting.save
      redirect_to meetings_url, notice: "Meeting created successfully."
    else
      render 'new'
    end
  end

  def edit
    @meeting = Meeting.find_by(id: params[:id])
  end

  def update
    @meeting = Meeting.find_by(id: params[:id])
    @meeting.held_on = params[:held_on]
    @meeting.course_id = params[:course_id]

    if @meeting.save
      redirect_to meetings_url, notice: "Meeting updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @meeting = Meeting.find_by(id: params[:id])
    @meeting.destroy

    redirect_to meetings_url, notice: "Meeting deleted."
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
  end

  def create
    @student = Student.new
    @student.first_name = params[:first_name]
    @student.last_name = params[:last_name]

    if @student.save
      redirect_to students_url, notice: "Student created successfully."
    else
      render 'new'
    end
  end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update
    @student = Student.find_by(id: params[:id])
    @student.first_name = params[:first_name]
    @student.last_name = params[:last_name]

    if @student.save
      redirect_to students_url, notice: "Student updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find_by(id: params[:id])
    @student.destroy

    redirect_to students_url, notice: "Student deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/edit.html.erb
<h1>Editing Attendance #<%= @attendance.id %></h1>

<%= form_tag(attendance_url(@attendance), method: 'patch') do %>
  <div>
    <%= label_tag :meeting_id %><br />
    <%= number_field_tag :meeting_id, @attendance.meeting_id %>
  </div>

  <div>
    <%= label_tag :student_id %><br />
    <%= number_field_tag :student_id, @attendance.student_id %>
  </div>

  <div>
    <%= submit_tag "Update Attendance" %>
  </div>
<% end %>

app/views/attendances/index.html.erb
<h1>Attendances</h1>

<p><%= link_to 'Add a New Attendance', new_attendance_url %></p>

<table>
  <thead>
    <tr>
      <th>Meeting</th>
      <th>Student</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @attendances.each do |attendance| %>
    <tr>
      <td><%= attendance.meeting_id %></td>
      <td><%= attendance.student_id %></td>
      <td><%= link_to 'Show', attendance_url(attendance) %></td>
      <td><%= link_to 'Edit', edit_attendance_url(attendance) %></td>
      <td><%= link_to 'Destroy', attendance_url(attendance), method: 'delete', data: { confirm: "Do you really want to delete this attendance?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= form_tag(attendances_url, method: 'post') do %>
  <div>
    <%= label_tag :meeting_id %><br />
    <%= number_field_tag :meeting_id %>
  </div>

  <div>
    <%= label_tag :student_id %><br />
    <%= number_field_tag :student_id %>
  </div>

  <div>
    <%= submit_tag "Create Attendance" %>
  </div>
<% end %>

app/views/attendances/show.html.erb
<h1>Attendance #<%= @attendance.id %></h1>

<dl>
  <dt>Meeting</dt>
  <dd><%= @attendance.meeting_id %></dd>

  <dt>Student</dt>
  <dd><%= @attendance.student_id %></dd>

</dl>

app/views/courses/edit.html.erb
<h1>Editing Course #<%= @course.id %></h1>

<%= form_tag(course_url(@course), method: 'patch') do %>
  <div>
    <%= label_tag :department %><br />
    <%= text_field_tag :department, @course.department %>
  </div>

  <div>
    <%= label_tag :number %><br />
    <%= text_field_tag :number, @course.number %>
  </div>

  <div>
    <%= label_tag :title %><br />
    <%= text_field_tag :title, @course.title %>
  </div>

  <div>
    <%= submit_tag "Update Course" %>
  </div>
<% end %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<p><%= link_to 'Add a New Course', new_course_url %></p>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Number</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
    <tr>
      <td><%= course.department %></td>
      <td><%= course.number %></td>
      <td><%= course.title %></td>
      <td><%= link_to 'Show', course_url(course) %></td>
      <td><%= link_to 'Edit', edit_course_url(course) %></td>
      <td><%= link_to 'Destroy', course_url(course), method: 'delete', data: { confirm: "Do you really want to delete this course?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= form_tag(courses_url, method: 'post') do %>
  <div>
    <%= label_tag :department %><br />
    <%= text_field_tag :department %>
  </div>

  <div>
    <%= label_tag :number %><br />
    <%= text_field_tag :number %>
  </div>

  <div>
    <%= label_tag :title %><br />
    <%= text_field_tag :title %>
  </div>

  <div>
    <%= submit_tag "Create Course" %>
  </div>
<% end %>

app/views/courses/show.html.erb
<h1>Course #<%= @course.id %></h1>

<dl>
  <dt>Department</dt>
  <dd><%= @course.department %></dd>

  <dt>Number</dt>
  <dd><%= @course.number %></dd>

  <dt>Title</dt>
  <dd><%= @course.title %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rollcall</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meetings/edit.html.erb
<h1>Editing Meeting #<%= @meeting.id %></h1>

<%= form_tag(meeting_url(@meeting), method: 'patch') do %>
  <div>
    <%= label_tag :held_on %><br />
    <%= text_field_tag :held_on, @meeting.held_on %>
  </div>

  <div>
    <%= label_tag :course_id %><br />
    <%= number_field_tag :course_id, @meeting.course_id %>
  </div>

  <div>
    <%= submit_tag "Update Meeting" %>
  </div>
<% end %>

app/views/meetings/index.html.erb
<h1>Meetings</h1>

<p><%= link_to 'Add a New Meeting', new_meeting_url %></p>

<table>
  <thead>
    <tr>
      <th>Held on</th>
      <th>Course</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @meetings.each do |meeting| %>
    <tr>
      <td><%= meeting.held_on %></td>
      <td><%= meeting.course_id %></td>
      <td><%= link_to 'Show', meeting_url(meeting) %></td>
      <td><%= link_to 'Edit', edit_meeting_url(meeting) %></td>
      <td><%= link_to 'Destroy', meeting_url(meeting), method: 'delete', data: { confirm: "Do you really want to delete this meeting?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= form_tag(meetings_url, method: 'post') do %>
  <div>
    <%= label_tag :held_on %><br />
    <%= text_field_tag :held_on %>
  </div>
  
  <div>
	<select name="course_id">
		<% @courses.each do |course| %>
			<option value= <%= course["id"] %> > <%= course["title"] %> </option>
		<% end %>
	</select>
  </div>

  <div>
    <%= submit_tag "Create Meeting" %>
  </div>
<% end %>

app/views/meetings/show.html.erb
<h1>Meeting #<%= @meeting.id %></h1>

<dl>
  <dt>Held on</dt>
  <dd><%= @meeting.held_on %></dd>

  <dt>Course</dt>
  <dd><%= @meeting.course_id %></dd>

</dl>

app/views/students/edit.html.erb
<h1>Editing Student #<%= @student.id %></h1>

<%= form_tag(student_url(@student), method: 'patch') do %>
  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name, @student.first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name, @student.last_name %>
  </div>

  <div>
    <%= submit_tag "Update Student" %>
  </div>
<% end %>

app/views/students/index.html.erb
<h1>Students</h1>

<p><%= link_to 'Add a New Student', new_student_url %></p>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td><%= link_to 'Show', student_url(student) %></td>
      <td><%= link_to 'Edit', edit_student_url(student) %></td>
      <td><%= link_to 'Destroy', student_url(student), method: 'delete', data: { confirm: "Do you really want to delete this student?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_tag(students_url, method: 'post') do %>
  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name %>
  </div>

  <div>
    <%= submit_tag "Create Student" %>
  </div>
<% end %>

app/views/students/show.html.erb
<h1>Student #<%= @student.id %></h1>

<dl>
  <dt>First name</dt>
  <dd><%= @student.first_name %></dd>

  <dt>Last name</dt>
  <dd><%= @student.last_name %></dd>

</dl>